### ISSUE TITLE
GPU Memory leak!!

### ISSUE THREAD

**Issue by qhFang** [Karbo123/torch_kdtree#1]
I just use a tensor to create a kdtree using your code, When I delete the kdtree, the gpu memory usage in nvidia-smi can't decrease even after I use torch.cuda.empty_cache. 
In my network, every epoch the kdtree will use 2MiB gpu memory, and won't release it.  
How can I solve this problem.

The Code is simple:
spc = torch.rand(NUM, 3)
tree = torch_kdtree.torchBuildCUDAKDTree(spc)
del tree
torch.cuda.empty_cache()

**Comment by Karbo123** [comment]
Yeah, that is a problem, as we haven't checked the codes of cuda memory allocation yet. We will check the codes as soon as possible.

**Comment by Karbo123** [comment]
The cuda memory leakage problem is fixed in the latest commit. Test script is provided in `test/test_memleak.py`. 
Further questions are welcome.

**Comment by QHFang** [comment]
Thank you for your reply.
Btw， there are still two question I found.
1. The tree can't be built when the number of points is equal of less than 2^14. I think the reason is that the number of threads and blocks is fixed. When I decrease the blocks from 32 to 16, it work well with 2^14 points.
2. And if I want to build a tree with N numbers while log2(N) is not a integer, it can't be built.

**Comment by Karbo123** [comment]
Thanks, and they are really some problems.
The codes of building kdtree is modified from another repo [KdTreeGPU](https://github.com/johnarobinson77/KdTreeGPU), and since KdTreeGPU is limited to those two problems you mentioned, so for now our torch_kdtree also suffers from these problems. This repo is still under development, functions could be enhanced and problems could be fixed in the future releases.

**Comment by QHFang** [comment]
I got it. Thank you for your reply.
